### ISSUE TITLE
Naming for analysis modes

### ISSUE THREAD

**Issue by chporter** [DSSAT/pythia#2]
Initial suggestions:
1. "per pixel" - raw results of simulations
2. "per pixel with weight" - multiply each pixel result by WEIGHT variable
3. "per pixel average" - average over time for each pixel
4. "per pixel average with weight" - average over time for each pixel, multiplied by WEIGHT variable
5. "aggregate" - aggregate over area with no weighting or averaging
6. "aggregate with weight" - aggregate over area with weighting specified by WEIGHT variable
7. "aggregate average" - aggregate over area with no weighting, then average over time
8. "aggregate average with weight" - aggregate over area with weighting specified by WEIGHT variable, then average over time 

Pixel by pixel results need also lat and long.
Time series results need also year.

**Comment by chporter** [comment]
After conversation with @frostbytten , perhaps "with weight" could be a separate attribute, leaving four options:
1. "per pixel" -> # rows = # pixels x # years
2. "per pixel average" -> # rows = # pixels
3. "aggregate" -> # rows = # years
4. "aggregate average" -> # rows = 1

These 4 options determine the number of outputs. Both weighted and unweighted could be specified for the same option.

**Comment by frostbytten** [comment]
We have moved this functionality to post processing scripts. This allows pythia itself to stay relatively clean.
